
workspace {
    id = "12334567abcd"
}

# build projects
target build {
    depends_on = [ target.^build ]
}

# test projects
target test {
    depends_on = [ target.build ]
}

# generate artifacts
target dist {
    managed = false
    depends_on = [ target.build
                   target.^dist.toto ]
}

# plan deployment
target plan {
    rebuild = terrabuild.retry
    depends_on = [ target.dist
                   target.^plan ]
}
# run deployment
target apply {
    managed = false
    depends_on = [ target.plan
                   target.^apply ]
}

target destroy {
    managed = false
}

target serve {
    depends_on = [ target.^serve ]
}

variable toto {
    defaults = "tagaga"
    description = "pouet pouet"
}

locals {
    is_local_build = terrabuild.configuration == "local"
    target_env = terrabuild.environment ?? "dev"

    dotnet = { config: local.is_local_build && local.target_env == "dev" ? "Debug" : "Release" }

    terraform = { apps: local.target_env
                  infra: local.target_env ~= "^prod" ? "prod" : "dev" }

    runtimes = {
        dotnet: terrabuild.ci ? "linux-x64" : "linux-arm64"
        docker: terrabuild.ci ? ["linux/amd64"] : ["linux/arm64"]
    }

    docker_tags = {
        dotnet_sdk: "9.0.300" # https://mcr.microsoft.com/artifact/mar/dotnet/sdk/tags
        dotnet_runtime: "9.0.5" # https://mcr.microsoft.com/artifact/mar/dotnet/runtime/tags
        nodejs: "22.16.0-alpine3.22" # https://hub.docker.com/_/node/tags
        nginx: "1.28.0-alpine" # https://hub.docker.com/_/nginx/tags
        openapi: "v7.13.0" # https://hub.docker.com/r/openapitools/openapi-generator-cli/tags
        terraform: "1.12.2" # https://hub.docker.com/_/hashicorp-terraform/tags
    }
}

extension @dotnet {
    container = local.is_local_build ? nothing : "mcr.microsoft.com/dotnet/sdk:${local.docker_tags.dotnet_sdk}"
    defaults {
        runtime = local.runtimes.dotnet
        configuration = local.dotnet.config
    }
}

extension @docker {
    defaults {
        platforms = local.runtimes.docker
        image = "ghcr.io/magnusopera/${terrabuild.project}"
    }
}

extension @npm {
    container = local.is_local_build ? nothing : "node:${local.docker_tags.nodejs}"
}

extension @openapi {
    container = "openapitools/openapi-generator-cli:${local.docker_tags.openapi}"
}

extension @terraform {
    container = "hashicorp/terraform:${local.docker_tags.terraform}"
    variables = [ "GOOGLE_APPLICATION_CREDENTIALS"
                  "TF_*" ]
}
