
# workspace block
workspace {
    # workspace definition
    id = "12334567abcd"
    ignores = [ "obj/**" ]
    version = "~0.157.0"

    unknown = "toto"
}

# target block
target build {
    # target definition
    depends_on = [ # comment in list
                   target.^build ]
    cache = "local"
    rebuild = true
    idempotent = false
    inline = true

    unknown = "toto"
}

# extension
extension @dotnet {
    # extension
    container = local.is_local_build ? nothing : "mcr.microsoft.com/dotnet/sdk:${local.docker_tags.dotnet_sdk}"
    platform = "linux/arm64"
    variables = [ "GOOGLE_*" ]
    script = "../dotnet.fsx"
    unknown = "toto"

    defaults {
        runtime = local.runtimes.dotnet
        configuration = local.dotnet.config
    }
}

# variable
variable toto {
    # bindings
    defaults = "tagada"
    description = "this is the toto variable"

    unknown = "toto"
}


# locals
locals {
    # bindings
    is_local_build = terrabuild.configuration == "local"
    target_env = terrabuild.environment ?? "dev"

    dotnet = { # comment in map
               config: local.is_local_build # comments inside expression
                       && local.target_env == "dev" ? "Debug" : "Release" }

    terraform = { apps: local.target_env
                  infra: local.target_env ~= "^prod" ? "prod" : "dev" }

    runtimes = {
        dotnet: terrabuild.ci ? "linux-x64" : "linux-arm64"
        docker: terrabuild.ci ? ["linux/amd64"] : ["linux/arm64"]
    }

    docker_tags = {
        dotnet_sdk: "9.0.300" # https://mcr.microsoft.com/artifact/mar/dotnet/sdk/tags
        dotnet_runtime: "9.0.5" # https://mcr.microsoft.com/artifact/mar/dotnet/runtime/tags
        nodejs: "22.16.0-alpine3.22" # https://hub.docker.com/_/node/tags
        nginx: "1.28.0-alpine" # https://hub.docker.com/_/nginx/tags
        openapi: "v7.13.0" # https://hub.docker.com/r/openapitools/openapi-generator-cli/tags
        terraform: "1.12.2" # https://hub.docker.com/_/hashicorp-terraform/tags
    }
}

# unknown block
unknown {
}

unknown titi {
}

# invalid identifier
target Titi {
}
